### PR TITLE
Implement middleware concept and their tests

### PR DESCRIPTION
**Pull request by dhia-gharsallaoui**

### CODE REVIEW

**Comment by wneessen** [comment]
Thank you very much for the PR! Much appreciated!

I feel though, that the `Client` might be the wrong part for this extension. The Client only handles connections to a mail server, so the Middleware would only work when you actually use `Send()` to delivery the mail via a mail server. We have a lot of `WriteTo*()` methods on the `Msg` itself, which i. e. write the Msg into a file or use a local sendmail installation to deliver the mail. In these cases the Middleware would not be applied.

Do you think it would make sense to rather have the Middleware integrated in the `Msg` or even the `Msgwriter` instead to cover all current (and possibly future) cases? Also please fix the GolangCI Lint finding.

Looking forward to your comments!

**Comment by dhia-gharsallaoui** [comment]
Sounds cool, how would we add global middleware? Do you have any clue?

**Comment by wneessen** [comment]
Since all `msg.WriteTo*` methods basically rely on https://github.com/wneessen/go-mail/blob/main/msg.go#L661  and correspodingly on https://github.com/wneessen/go-mail/blob/main/msgwriter.go#L61, I suggest to have the `Middleware` type implemented on either of those two types and then have the middleware applied in one of the two methods: `msg.WriteTo()` or `msgwriter.writeMsg()`. I think that's a central place that would allow the middleware to be applied for either the msg.WriteTo*() methods as well as any client.Send*() method.

**Comment by dhia-gharsallaoui** [comment]
It's sound cool to rattach the middleware to the `msgWriter`. In this case I think we need to have the possibility to inject the msgWriter in the client like `WithMsgWriter`.
In this case I suggest the following:

- Add `msgWriter` to the Client struct
- Add the `msgWriter` argument in `msg.WriteTo()`.
- In `msg.WriteTo()` check if there is `msgWriter` if exist use it otherwise create a new one.
- Add `middlewares` to the `msgWriter` struct.
- Create the methods `msgWriter.AddMiddleware` and `msgWriter.applyMiddlewares` attached to `msgWriter`.
- Use `msgWriter.applyMiddlewares` in the `msgwriter.writeMsg()`
- Maybe we need also a `msgWriter` factory

Looking forward to your comments!

**Comment by wneessen** [comment]
I fear that route is will not really work, since i. e. in step 3 we have no reference to the `Client`, so we would need to make the message aware of the Client which is impractical. Giving it a further though, I believe the msgWriter route is too complex and not worth it. It's probably best to use the `Msg` route instead.

- Implement thte Middleware on Msg and add it to the Msg struct
- Since msgWriter is basically only used in `msg.WriteTo` and all other methods use `WriteTo` to access the msgWriter, that would the be the central point to apply the middleware just before the msgWriter is executed.

This way we keep the complexity simple and can handle all msg.WriteTo methods as well as the Client.Send methods.

What do you think?

**Comment by wneessen** [comment]
You have a good point and I agree with you. I'd say, let stop discussing and see what can be built from this brainstorming! :) Let me know if I can be of any assistance.

**Comment by dhia-gharsallaoui** [comment]
@wneessen feel free to review and give your remarks.

**Comment by wneessen** [comment]
Looks awesome! Thanks again for this cool feature!

**Comment by dhia-gharsallaoui** [comment]
@wneessen  can you share a new release containing this feature please?

**Comment by wneessen** [comment]
Yes. the release is planed for this morning. I am just waiting for PR #54 to complete.

**Pull request merged**
