### PR TITLE
Add default ports and fallback behavior for SSL and TLS

### LINKED ISSUE #105: Use appropriate standard port when setting SSL/TLS
### Is your feature request related to a problem? Please describe.

When using SSL or STARTTLS, the default port 25 is always used, which is against best practices as described in [RFC8314, section 3.3](https://datatracker.ietf.org/doc/html/rfc8314#section-3.3).

I'm willing to implement and send a PR if this enhancement is accepted.

### Describe the solution you'd like

1. `WithSSL()` to use the port default of 465, unless `WithPort()` is called;
2. `WithTLSPolicy()` with `TLSMandatory` or `TLSOpportunistic` to use port 587, and in case of the latter use fallback to port 25;

### Describe alternatives you've considered

Explicitly setting the port number with `WithPort(587)` works in my case. My mail server does not allow fallback to plain text SMTP on port 25. But if it where the case, I expect that `TLSOpportunistic` would not work as intended, as it will always try to use port 587, instead of falling back to 25.

### Additional context

To reproduce:

```
client, err := mail.NewClient(host,
	mail.WithSSL(),
	mail.WithSMTPAuth(mail.SMTPAuthPlain),
	mail.WithUsername(user),
	mail.WithPassword(password),
)
```

Or

```
client, err := mail.NewClient(host,
	mail.WithTLSPolicy(mail.TLSMandatory),
	mail.WithSMTPAuth(mail.SMTPAuthPlain),
	mail.WithUsername(user),
	mail.WithPassword(password),
)
```

Will result in connection failures to compliant hosts.

The above was inspired by the [bulk mailer example](https://go-mail.dev/examples/bulk-mailer/#hl-0-97), which doesn't seem to set an alternative port either.

### PR DESCRIPTION
**Pull request by wneessen**
Introduced default ports for SSL/TLS and STARTTLS connections in SMTP client. Also added fallback behavior, allowing the client to attempt connections on port 25 using plaintext if secured connections fail. Deprecated old methods and implemented new ones to enforce these changes effectively.

This is a copy of the PR #106 (muhlemmer:enhance-default-tls-port) by @muhlemmer. Since they unfortunately didn't reply in the PR anymore I cloned it instead. They will be fully attributed in the PR, though.

Closes #105 and #106.

### CODE REVIEW

**Comment by mitar** [comment]
This change makes no sense to me? It hard-codes port to 25 for non-TLS connections, it seems to me? There is no way to set `fallbackPort`?

Previous behavior made more sense to me. With `TLSOpportunistic`, I want to connect to port X, if it supports `STARTTLS`, use TLS, otherwise, use the same port, but just do not use TLS. Currently, if I use `SetTLSPortPolicy(TLSOpportunistic)`, if the server does not support `STARTTLS` on port X, it tries to connect to port 25 on that server - which might not even be available (or accessible - firewalls and stuff).

I do not get issue #105 either. Is this about behavior if one does not call `WithPort`? I think if `WithPort` is not made, then default should be to connect to port 25 (or 587?) and try STARTTLS on it, if it fails and `TLSOpportunistic` is set, use no TLS on same port. The behavior to try different ports makes no sense to me. You use one port, but potentially negotiate different configuration of how you use it. And `WithPort` is then used to configure which port is the one the client uses.

Luckily, `WithTLSPolicy` still works and if I use `WithTLSPolicy` it is exactly how I would want. Maybe just remove deprecation on it?

But I do think that connecting to multiple ports is a strange approach. That might be done by some higher-level library to auto-detect configuration of an unknown SMTP server. But not by a low-level library like this one where you generally know the server you are connecting to.

**Comment by mitar** [comment]
Also, interestingly, `SetTLSPolicy` was not market as deprecated.

**Comment by wneessen** [comment]
Hi @mitar,

thanks for raising your concerns. The main reason for #105 and therefore this change was, that we wanted to follow established standards, but I agree that not recognizing `WithPort()` when using `*TLSPortPolicy` is an oversight on my end. `WithPort` should always have higher priority over automations/auto-detections. I'll rework this patch taking your comments into consideration.

**Comment by mitar** [comment]
Sorry, which established standard suggest automatic use of port 25? [RFC section referenced from #105](https://datatracker.ietf.org/doc/html/rfc8314#section-3.3) does not mention so, to my understanding? It even says:

> However, to maximize the use of encryption for
   submission, it is desirable to support both mechanisms for Message
   Submission over TLS for a transition period of several years.  As a
   result, clients and servers SHOULD implement both STARTTLS on
   port 587 and Implicit TLS on port 465 for this transition period.
   Note that there is no significant difference between the security
   properties of STARTTLS on port 587 and Implicit TLS on port 465 if
   the implementations are correct and if both the client and the server
   are configured to require successful negotiation of TLS prior to
   Message Submission.

To me this reads really like "negotiate on the same port" - while 587 is the one where there can be `STARTTLS` or not.

**Comment by wneessen** [comment]
Correct. Before we were defaulting to port 25, which is not best practice. The fallback option was just to keep compatiblity with that behaviour. This will be reworked in #181

**Comment by wneessen** [comment]
@mitar The whole `TLSPortPolicy()` situation has been refined in #181. I've removed the deprecation notes and replaced them with recommendation notes instead. Also `TLSPortPolicy` (and the SSL equivalent) will not change the ports anymore, if the port has been set already otherwise (i. e. via `WithPort()`). I think this is a better solution now and given that the deprecation notes are gone, the users are free to chose either solution - either the "handholding" one or the "low-level" one.

**Comment by mitar** [comment]
Awesome, thanks!

**Pull request merged**
